export const pokemonList = [
  {
    name: "Aron",
    id: "304",
    img: "/imagenes/Pokemones/aron.png",
    type: ["Steel", "Rock"],
    weight: 60.0,
    heigth: 0.4,
    moves: ["Sturdy", "Rock-Head"],
    description:
      "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that projects its body.",
    hp: "050",
    atk: "070",
    def: "100",
    satk: "040",
    sdef: "040",
    spd: "030",
    primary_color: "#B7B9D0",
    secondary_color: "#B69E31",
  },
  {
    name: "Charmander",
    id: "004",
    img: "/imagenes/Pokemones/charmander.png",
    type: ["Fire"],
    weight: 8.5,
    heigth: 0.6,
    moves: ["Mega-Punch", "Fire-Punch"],
    description:
      "It has a preferencia for hot things. When it rans, steam is said to spout from the tip of its tail.",
    hp: "039",
    atk: "052",
    def: "043",
    satk: "060",
    sdef: "050",
    spd: "065",
    primary_color: "#F57D31",
    secondary_color: "",
  },
  {
    name: "Bulbasaur",
    id: "001",
    img: "/imagenes/Pokemones/bulbasaur.png",
    type: ["Grass", "Polson"],
    weight: 6.9,
    heigth: 0.7,
    moves: ["Chlorophyll", "Overgrow"],
    description:
      "There is a plant seed on its back right from the day this pokemon is born. The seed slowly grows larger.",
    hp: "045",
    atk: "049",
    def: "049",
    satk: "065",
    sdef: "065",
    spd: "045",
    primary_color: "#74CB48",
    secondary_color: "#A43E9E",
  },
  {
    name: "Squirtle",
    id: "007",
    img: "/imagenes/Pokemones/squirtle.png",
    type: ["Water"],
    weight: 9.0,
    heigth: 0.5,
    moves: ["Torrent", "Rain-Dish"],
    description: "When it retracts its long neck",
    hp: "045",
    atk: "049",
    def: "049",
    satk: "065",
    sdef: "065",
    spd: "045",
    primary_color: "#6493EB",
    secondary_color: "",
  },
  {
    name: "Ditto",
    id: "132",
    img: "/imagenes/Pokemones/ditto.png",
    type: ["Normal"],
    weight: 4.0,
    heigth: 0.3,
    moves: ["Limber", "Imposter"],
    description:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    hp: "048",
    atk: "048",
    def: "048",
    satk: "048",
    sdef: "048",
    spd: "048",
    primary_color: "#AAA67F",
    secondary_color: "",
  },
  {
    name: "Butterfree",
    id: "012",
    img: "/imagenes/Pokemones/butterfree.png",
    type: ["Bug", "Flying"],
    weight: 32.0,
    heigth: 1.1,
    moves: ["Compund-Eyes", "Tinted-Lens"],
    description:
      "In battle, it flops its wings at greta speed to release highly toxic dust into the air.",
    hp: "060",
    atk: "045",
    def: "050",
    satk: "090",
    sdef: "080",
    spd: "070",
    primary_color: "#A7B723",
    secondary_color: "#A891EC",
  },
  {
    name: "Gastly",
    id: "092",
    img: "/imagenes/Pokemones/gastly.png",
    type: ["Ghost", "Type"],
    weight: 0.1,
    heigth: 1.3,
    moves: ["Levitate"],
    description:
      "Born form gases, anyone would faint if engulled by its gaseous body, which contains poison.",
    hp: "030",
    atk: "035",
    def: "030",
    satk: "100",
    sdef: "035",
    spd: "080",
    primary_color: "#70559B",
    secondary_color: "#666666",
  },
  {
    name: "Pikachu",
    id: "025",
    img: "/imagenes/Pokemones/pikachu.png",
    type: ["Electric"],
    weight: 6.0,
    heigth: 0.4,
    moves: ["Mega-Punchy", "Pay-Day"],
    description:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    hp: "035",
    atk: "055",
    def: "040",
    satk: "050",
    sdef: "050",
    spd: "090",
    primary_color: "#F9CF30",
    secondary_color: "",
  },
  {
    name: "Mew",
    id: "152",
    img: "/imagenes/Pokemones/mew.png",
    type: ["Psychic"],
    weight: 4.0,
    heigth: 0.4,
    moves: ["Synchronize"],
    description:
      "When viewed through a microscope, this Pokemon's short, fine, delicate hair can be seen.",
    hp: "035",
    atk: "055",
    def: "040",
    satk: "050",
    sdef: "050",
    spd: "090",
    primary_color: "#FB5584",
    secondary_color: "",
  },
];
